name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.12'
        architecture: 'x64'
    - name: Install requirements
      run: |
        pip install -r requirements.txt
        pip install pyinstaller
        pip install nuitka
    - name: Create binary (nuitka)
      run: |
        python -m nuitka --mingw64 --standalone --onefile easy2homeassistant/easy2homeassistant.py --include-data-dir=easy2homeassistant/resources=resources
    - name: Upload binaries to release (nuitka)
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: easy2homeassistant.exe
        asset_name: easy2homeassistant.exe
        tag: ${{ github.ref }}
        overwrite: true
    #- name: Create binary (pyinstaller)
    #  run: |
    #    pyinstaller --onefile easy2homeassistant/easy2homeassistant.py
    #- name: Upload binaries to release (pyinstaller)
    #  uses: svenstaro/upload-release-action@v2
    #  with:
    #    repo_token: ${{ secrets.GITHUB_TOKEN }}
    #    file: dist/easy2homeassistant.exe
    #    asset_name: easy2homeassistant.exe
    #    tag: ${{ github.ref }}
    #    overwrite: true

