name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish binaries
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.12'
        architecture: 'x64'
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - name: Create binary
      uses: Nuitka/Nuitka-Action@main
      with:
        nuitka-version: main
        script-name: easy2homeassistant/easy2homeassistant.py
        mode: app
        include-data-dir: |
          easy2homeassistant/resources=resources
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/easy2homeassistant.exe
        asset_name: easy2homeassistant.exe
        tag: ${{ github.ref }}
        overwrite: true
