name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov
      - name: Test with pytest
        run: pytest --doctest-modules --junitxml=cover/test-results-${{ matrix.python-version }}.xml --cov=. --cov-report=xml --cov-report=html
      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: cover/test-results-${{ matrix.python-version }}.xml
        if: ${{ always() }}
